// Generated by Flutter Design Preview.

library flutter_design_preview_runner;

import 'package:flutter/material.dart';
import 'package:flutter_design_preview/flutter_design_preview.dart';

// {{builderImport}}
// {{widgetImports}}

void main() {
  final widgets = <String, PreviewWidget>{
    // {{widgetEntries}}
  };

  runApp(
    PreviewRunner(
      initialId: widgets.keys.first,
      widgets: widgets,
      builder: _templateBuilder,
    ),
  );
}

Widget _templateBuilder(PreviewWidget preview) {
  throw UnimplementedError('Runner template placeholder');
}
