name: _
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_design_preview:
    path: ../../packages/flutter_design_preview

flutter:
  uses-material-design: true
